<<<<<<< HEAD
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/components/providers";
=======
"use client";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { MockServiceProvider } from "@/components/mock-service-provider";
import { AuthProvider } from "@/contexts/AuthContext";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useMemo } from "react";

>>>>>>> repoB/master
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

<<<<<<< HEAD
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

=======
>>>>>>> repoB/master
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
<<<<<<< HEAD
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans text-[16px] antialiased`}>
        <Providers>
          <Toaster />
          {children}
        </Providers>
=======
  const queryClient = useMemo(() => new QueryClient(), []);
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} font-sans text-[16px] antialiased`} suppressHydrationWarning>
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <MockServiceProvider />
            {children}
          </AuthProvider>
        </QueryClientProvider>
>>>>>>> repoB/master
      </body>
    </html>
  );
}
